### PR TITLE
Add Keyboard shortcuts

### PR DESCRIPTION
**Pull request by cafca**
Hey Ray,

Thanks for the great extension, I use it all the time. I was missing keyboard shortcuts so I added some for the first four presets, mapped to Ctrl+F9 - Ctrl-F12, hope you like it. Users can also change keyboard shortcuts in Firefox extension settings. There is no license specified in the respository, you might want to add that, hope it's okay that I forked this.

So I factored out some of the functions from `Popup.js` in order to make them available in the background script as well and then added an event handler for the shortcuts in `background.js`.

Please say so if anything's missing here for you.

All the best,
Vincent

### CODE REVIEW

**Comment by ciex** [comment]
Hey @ray-lothian Please give me short feedback on whether or not you plan to merge this pull request. If you don't have time to look at it right now, that's okay, just please tell me your intentions.

**Comment by ciex** [comment]
hey @ray-lothian would you be okay if i republish this extension with keyboard shortcuts if you don't plan on merging this?

**Comment by ray-lothian** [comment]
apologies for the late reply. I barely have time to work on this extension. Would you like to be added as a developer to this project? If not you can fork and work on your extension.

**Comment by ciex** [comment]
Thanks for your reply. I'm really sorry if I was too pushy here but I use
this extension all the time and really wanted this.

Yes, please add me as a project member on Github. I will still not be able
to publish updates to the extension though - I can see that you have
published it for Chrome, Firefox, etc.If you don't know right away how to
grant me rights for that I can still just publish a fork.

I totally understand your situation with not having time for this due to
work, it's the common end to many open source projects :)

**Comment by ray-lothian** [comment]
I am going to push to the stores. No problem. Let me know when the new version is ready or you need help with the code.

**Comment by ray-lothian** [comment]
perfect! I just submitted the new version to the stores. few changes:

1. I moved the new FAQs to the FAQ page
2. I added support for multiple monitors (Chrome only)

**Pull request merged**
